const List<String> harryPotterNames = [
  // 🧙‍♂️ The Golden Trio
  'Harry James Potter',
  'Hermione Jean Granger',
  'Ronald Bilius Weasley',

  // 🧑‍🎓 Students & Friends
  'Neville Longbottom',
  'Ginny Weasley',
  'Luna Lovegood',
  'Dean Thomas',
  'Seamus Finnigan',
  'Lavender Brown',
  'Cho Chang',
  'Parvati Patil',
  'Padma Patil',
  'Cedric Diggory',
  'Lee Jordan',
  'Angelina Johnson',
  'Alicia Spinnet',
  'Katie Bell',
  'Pansy Parkinson',
  'Vincent Crabbe',
  'Gregory Goyle',
  'Draco Lucius Malfoy',

  // 🧙‍♀️ Hogwarts Staff & Order of the Phoenix
  'Albus Percival Wulfric Brian Dumbledore',
  'Minerva McGonagall',
  'Severus Snape',
  'Rubeus Hagrid',
  'Horace Slughorn',
  'Gilderoy Lockhart',
  'Filius Flitwick',
  'Pomona Sprout',
  'Sybill Trelawney',
  'Argus Filch',
  'Dolores Umbridge',
  'Remus Lupin',
  'Alastor Mad-Eye Moody',
  'Kingsley Shacklebolt',
  'Nymphadora Tonks',
  'Molly Weasley',
  'Arthur Weasley',

  // 🧛 Villains & Death Eaters
  'Tom Marvolo Riddle',
  'Bellatrix Lestrange',
  'Lucius Malfoy',
  'Narcissa Malfoy',
  'Peter Pettigrew',
  'Fenrir Greyback',
  'Igor Karkaroff',
  'Thorfinn Rowle',
  'Barty Crouch Jr.',

  // 🧙‍♂️ Ministry & Others
  'Barty Crouch Sr.',
  'Cornelius Fudge',
  'Percy Weasley',
  'Rita Skeeter',
  'Vernon Dursley',
  'Petunia Dursley',
  'Dudley Dursley',

  // 🧝 Magical Creatures & Ghosts
  'Dobby',
  'Kreacher',
  'Buckbeak',
  'Fawkes',
  'Nagini',
  'Nearly Headless Nick',
  'Moaning Myrtle',
  'The Bloody Baron',
  'The Grey Lady',
  'The Fat Friar',

  // 🧙‍♂️ Others
  'Sirius Black',
  'Regulus Arcturus Black',
  'Nicholas Flamel',
];
